### PR TITLE
Fix the NaN stddev

### LINKED ISSUE #69: panic: json: unsupported value: NaN
Using current master (bbaf008) from observability demo repository, and the organization `carlosms-test-org`, it fails with this log:
```
identity-matching_1      | time="2019-10-03T08:54:47Z" level=info msg="Using caching for external matching" cachePath=cache-external.csv
identity-matching_1      | time="2019-10-03T08:54:47Z" level=info msg="Dumping CachedMatcher cache."
identity-matching_1      | time="2019-10-03T08:54:47Z" level=info msg="looking for people in commits"
identity-matching_1      | time="2019-10-03T08:54:47Z" level=info msg="not cached in cache-raw.csv, loading from the database"
identity-matching_1      | time="2019-10-03T08:54:47Z" level=info msg="caching the result to cache-raw.csv"
identity-matching_1      | time="2019-10-03T08:54:47Z" level=info msg="found people" elapsed=9.72824ms people=1
identity-matching_1      | time="2019-10-03T08:54:47Z" level=info msg="reducing people"
identity-matching_1      | time="2019-10-03T08:54:48Z" level=warning msg="unable to find users for email: carlos.martin.sanchez@gmail.com"
identity-matching_1      | time="2019-10-03T08:54:48Z" level=warning msg="no matches for person :carlos martin||carlos.martin.sanchez@gmail.com"
identity-matching_1      | time="2019-10-03T08:54:48Z" level=info msg="reduced people" elapsed=889.145294ms people=1
identity-matching_1      | time="2019-10-03T08:54:48Z" level=info msg="primary names are set" elapsed="2.417µs"
identity-matching_1      | time="2019-10-03T08:54:48Z" level=info msg="primary emails are set" elapsed="1.465µs"
identity-matching_1      | time="2019-10-03T08:54:48Z" level=info msg="storing people"
identity-matching_1      | time="2019-10-03T08:54:48Z" level=info msg="stored people" elapsed=5.782553ms path=identities
identity-matching_1      | panic: json: unsupported value: NaN
identity-matching_1      | 
identity-matching_1      | goroutine 1 [running]:
identity-matching_1      | github.com/src-d/identity-matching/reporter.Write()
identity-matching_1      | 	/go/src/identity-matching/reporter/reporter.go:38 +0x10b
identity-matching_1      | main.main()
identity-matching_1      | 	/go/src/identity-matching/cmd/match-identities/main.go:111 +0x120a

```

### PR DESCRIPTION
**Pull request by vmarkovtsev**
Signed-off-by: Vadim Markovtsev <vadim@sourced.tech>

Fixes #69

### CODE REVIEW

File: matching.go [hunk 1]
```diff
@@ -209,6 +209,8 @@ func ReducePeople(people People, matcher external.Matcher, blacklist Blacklist,
 	mean, std := stat.MeanStdDev(componentsSize, nil)
 	if mean != mean {
 		mean = 0
+	}
+	if std != std {
```
Comment (carlosms) [inline matching.go]: Does this have any advantage over `math.IsNan(std)`?

Comment (vmarkovtsev) [reply matching.go]: https://github.com/golang/go/blob/master/src/math/bits.go#L39
